export interface FreeMockTestItem {
  id: string;
  mockNumber: number;
  code: string;
  title: string;
  badge: string;
  pattern: string;
  totalQuestions: number;
  totalMarks: number;
  durationMinutes: number;
  difficulty: "Standard" | "Moderate" | "Challenging";
  focusTopics: string[];
  keyHighlights: string;
  recommendedTime: string;
  subjects: {
    physics: { questions: number; mcq: number; numerical: number };
    chemistry: { questions: number; mcq: number; numerical: number };
    maths: { questions: number; mcq: number; numerical: number };
  };
  playerUrl: string;
}

export const FREE_MOCKS_DATA: FreeMockTestItem[] = [
  {
    id: "MFT-1.pdf",
    mockNumber: 1,
    code: "MFT-01",
    title: "JEE Main Full Mock Test 01",
    badge: "Most Popular",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Standard",
    focusTopics: ["Kinematics & Laws of Motion", "Chemical Bonding & Stoichiometry", "Matrices, Determinants & Quad Equations"],
    keyHighlights: "Ideal diagnostic test for benchmarking your baseline All-India percentile across complete Class 11-12 syllabus.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-1.pdf",
  },
  {
    id: "MFT-2.pdf",
    mockNumber: 2,
    code: "MFT-02",
    title: "JEE Main Full Mock Test 02",
    badge: "High Yield",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Standard",
    focusTopics: ["Electrodynamics & Capacitors", "Thermodynamics & Equilibrium", "Calculus & Limits/Continuity"],
    keyHighlights: "High weightage focus testing conceptual clarity and numerical solving speed under timed pressure.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-2.pdf",
  },
  {
    id: "MFT-3.pdf",
    mockNumber: 3,
    code: "MFT-03",
    title: "JEE Main Full Mock Test 03",
    badge: "Trending",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Moderate",
    focusTopics: ["Rotational Motion & Gravitation", "Organic Basics & Hydrocarbons", "Coordinate Geometry & Straight Lines"],
    keyHighlights: "Strengthens your core problem-solving intuition with multi-concept physics mechanics and organic reactions.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-3.pdf",
  },
  {
    id: "MFT-4.pdf",
    mockNumber: 4,
    code: "MFT-04",
    title: "JEE Main Full Mock Test 04",
    badge: "Recommended",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Moderate",
    focusTopics: ["Modern Physics & Semiconductor", "Coordination Compounds & p-Block", "Vectors & 3D Geometry"],
    keyHighlights: "Focus on high-scoring scoring zones: Modern Physics, 3D Geometry, and Coordination Compounds.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-4.pdf",
  },
  {
    id: "MFT-5.pdf",
    mockNumber: 5,
    code: "MFT-05",
    title: "JEE Main Full Mock Test 05",
    badge: "Balanced",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Standard",
    focusTopics: ["Optics (Ray & Wave)", "Aldehydes, Ketones & Amines", "Definite Integration & Area Under Curves"],
    keyHighlights: "Balanced paper modeled on recent Shift-1/Shift-2 difficulty distributions.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-5.pdf",
  },
  {
    id: "MFT-6.pdf",
    mockNumber: 6,
    code: "MFT-06",
    title: "JEE Main Full Mock Test 06",
    badge: "Speed Booster",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Moderate",
    focusTopics: ["Thermodynamics & KTG", "Solutions & Electrochemistry", "Differential Equations & Probability"],
    keyHighlights: "Designed to train time allocation, negative marks reduction, and quick numerical question selection.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-6.pdf",
  },
  {
    id: "MFT-7.pdf",
    mockNumber: 7,
    code: "MFT-07",
    title: "JEE Main Full Mock Test 07",
    badge: "Advanced Level",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Challenging",
    focusTopics: ["Oscillations, SHM & Waves", "d & f Block Elements, Metallurgy", "Conic Sections (Parabola, Ellipse, Hyperbola)"],
    keyHighlights: "A slightly tougher test crafted to prepare aspirants for tricky question variants in JEE Main 2027.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-7.pdf",
  },
  {
    id: "MFT-8.pdf",
    mockNumber: 8,
    code: "MFT-08",
    title: "JEE Main Full Mock Test 08",
    badge: "Predictive",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Standard",
    focusTopics: ["Electromagnetic Induction & AC", "Chemical Kinetics & Surface Chemistry", "Permutations, Combinations & Binomial"],
    keyHighlights: "Curated high-frequency question patterns from recent NTA question sets with rigorous verification.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-8.pdf",
  },
  {
    id: "MFT-9.pdf",
    mockNumber: 9,
    code: "MFT-09",
    title: "JEE Main Full Mock Test 09",
    badge: "Percentile Booster",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Moderate",
    focusTopics: ["Fluids, Elasticity & Thermal Properties", "Biomolecules & Practical Chemistry", "Complex Numbers & Quadratic"],
    keyHighlights: "Targets the crucial 99-percentile boundary questions in Chemistry and Mathematics.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-9.pdf",
  },
  {
    id: "MFT-10.pdf",
    mockNumber: 10,
    code: "MFT-10",
    title: "JEE Main Full Mock Test 10",
    badge: "Grand Final Mock",
    pattern: "Official NTA 75-Q CBT Pattern",
    totalQuestions: 75,
    totalMarks: 300,
    durationMinutes: 180,
    difficulty: "Standard",
    focusTopics: ["Comprehensive Full Syllabus PCM", "Full NTA Benchmark Standard", "All High-Yield Units Covered"],
    keyHighlights: "The definitive full mock test for your final readiness check before appearing for the real exam.",
    recommendedTime: "180 Mins",
    subjects: {
      physics: { questions: 25, mcq: 20, numerical: 5 },
      chemistry: { questions: 25, mcq: 20, numerical: 5 },
      maths: { questions: 25, mcq: 20, numerical: 5 },
    },
    playerUrl: "/exam/player?id=MFT-10.pdf",
  },
];
